[project]
name = "secure-rest-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pwdlib[argon2]>=0.3.1",
    "pyjwt>=2.15.0",
    "sqlalchemy>=2.0.54",
]

[dependency-groups]
dev = [
    "bandit>=1.9.4",
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]
